# Generated by Django 5.1.4 on 2025-02-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('loc', models.CharField(max_length=100)),
                ('mob', models.IntegerField()),
                ('pdf', models.FileField(upload_to='files')),
            ],
        ),
    ]
